/* Generated by Yosys 0.11+10 (git sha1 4871d8f19, clang 6.0.0-1ubuntu2 -fPIC -Os) */

module MyFSM(in, clk, rst, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire \cS[0] ;
  wire \cS[1] ;
  wire \cS[2] ;
  input clk;
  input in;
  wire \nS[0] ;
  wire \nS[1] ;
  wire \nS[2] ;
  output out;
  input rst;
  INV_X16 _11_ (
    .I(\cS[1] ),
    .ZN(_01_)
  );
  OR3_X2 _12_ (
    .A1(\cS[2] ),
    .A2(_01_),
    .A3(\cS[0] ),
    .Z(_02_)
  );
  INV_X1 _13_ (
    .I(\cS[2] ),
    .ZN(_03_)
  );
  NAND4_X2 _14_ (
    .A1(in),
    .A2(_03_),
    .A3(_01_),
    .A4(\cS[0] ),
    .ZN(_04_)
  );
  AND2_X2 _15_ (
    .A1(_02_),
    .A2(_04_),
    .Z(_05_)
  );
  BUF_X16 _16_ (
    .I(_05_),
    .Z(\nS[0] )
  );
  INV_X1 _17_ (
    .I(in),
    .ZN(_06_)
  );
  AOI21_X2 _18_ (
    .A1(_02_),
    .A2(_04_),
    .B(_06_),
    .ZN(_07_)
  );
  BUF_X16 _19_ (
    .I(_07_),
    .Z(\nS[1] )
  );
  NOR2_X2 _20_ (
    .A1(in),
    .A2(_02_),
    .ZN(_08_)
  );
  BUF_X16 _21_ (
    .I(_08_),
    .Z(\nS[2] )
  );
  NOR4_X2 _22_ (
    .A1(_06_),
    .A2(_03_),
    .A3(\cS[1] ),
    .A4(\cS[0] ),
    .ZN(_09_)
  );
  BUF_X8 _23_ (
    .I(_09_),
    .Z(out)
  );
  INV_X1 _24_ (
    .I(rst),
    .ZN(_10_)
  );
  BUF_X8 _25_ (
    .I(_10_),
    .Z(_00_)
  );
  DFFSNQ_X1 _26_ (
    .CLK(clk),
    .D(\nS[0] ),
    .Q(\cS[0] ),
    .SN(_00_)
  );
  DFFRNQ_X1 _27_ (
    .CLK(clk),
    .D(\nS[1] ),
    .Q(\cS[1] ),
    .RN(_00_)
  );
  DFFRNQ_X1 _28_ (
    .CLK(clk),
    .D(\nS[2] ),
    .Q(\cS[2] ),
    .RN(_00_)
  );
endmodule
