/* Generated by Yosys 0.11+10 (git sha1 4871d8f19, clang 6.0.0-1ubuntu2 -fPIC -Os) */

module top(clk, a, b, c, d, x);
  wire _0_;
  wire _1_;
  wire _2_;
  input a;
  input b;
  input c;
  input clk;
  input d;
  output x;
  XOR2_X1 _3_ (
    .A1(d),
    .A2(c),
    .Z(_0_)
  );
  XNOR2_X1 _4_ (
    .A1(b),
    .A2(a),
    .ZN(_1_)
  );
  XNOR2_X1 _5_ (
    .A1(_0_),
    .A2(_1_),
    .ZN(_2_)
  );
  DFFRNQ_X1 _6_ (
    .CLK(clk),
    .D(_2_),
    .Q(x),
    .RN(1'b1)
  );
endmodule
