/* Generated by Yosys 0.11+10 (git sha1 4871d8f19, clang 6.0.0-1ubuntu2 -fPIC -Os) */

module top(clk, p, q, a, b, x, y);
  wire _0_;
  wire _1_;
  wire _2_;
  input a;
  input b;
  input clk;
  input p;
  input q;
  output x;
  output y;
  NAND2_X2 _3_ (
    .A1(b),
    .A2(a),
    .ZN(_0_)
  );
  XNOR2_X1 _4_ (
    .A1(q),
    .A2(_0_),
    .ZN(_1_)
  );
  XNOR2_X1 _5_ (
    .A1(p),
    .A2(_0_),
    .ZN(_2_)
  );
  DFFRNQ_X1 _6_ (
    .CLK(clk),
    .D(_2_),
    .Q(x),
    .RN(1'b1)
  );
  DFFRNQ_X1 _7_ (
    .CLK(clk),
    .D(_1_),
    .Q(y),
    .RN(1'b1)
  );
endmodule
