/* Generated by Yosys 0.11+10 (git sha1 4871d8f19, clang 6.0.0-1ubuntu2 -fPIC -Os) */

module top(clk, a, b, c, x, y, z);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  input [7:0] a;
  input [7:0] b;
  input [7:0] c;
  input clk;
  output [15:0] x;
  output [15:0] y;
  output [15:0] z;
  XOR2_X1 _27_ (
    .A1(c[0]),
    .A2(c[4]),
    .Z(_00_)
  );
  OR2_X1 _28_ (
    .A1(c[2]),
    .A2(c[6]),
    .Z(_09_)
  );
  NAND2_X1 _29_ (
    .A1(c[2]),
    .A2(c[6]),
    .ZN(_10_)
  );
  NAND2_X1 _30_ (
    .A1(_09_),
    .A2(_10_),
    .ZN(_11_)
  );
  NAND2_X2 _31_ (
    .A1(c[0]),
    .A2(c[4]),
    .ZN(_12_)
  );
  NOR2_X1 _32_ (
    .A1(c[1]),
    .A2(c[5]),
    .ZN(_13_)
  );
  NAND2_X2 _33_ (
    .A1(c[1]),
    .A2(c[5]),
    .ZN(_14_)
  );
  OAI21_X2 _34_ (
    .A1(_12_),
    .A2(_13_),
    .B(_14_),
    .ZN(_15_)
  );
  XNOR2_X1 _35_ (
    .A1(_11_),
    .A2(_15_),
    .ZN(_05_)
  );
  XOR2_X1 _36_ (
    .A1(c[3]),
    .A2(c[7]),
    .Z(_16_)
  );
  AND2_X1 _37_ (
    .A1(c[2]),
    .A2(c[6]),
    .Z(_17_)
  );
  AOI21_X2 _38_ (
    .A1(_09_),
    .A2(_15_),
    .B(_17_),
    .ZN(_18_)
  );
  XNOR2_X1 _39_ (
    .A1(_16_),
    .A2(_18_),
    .ZN(_06_)
  );
  NOR2_X1 _40_ (
    .A1(c[3]),
    .A2(c[7]),
    .ZN(_19_)
  );
  NAND2_X1 _41_ (
    .A1(c[3]),
    .A2(c[7]),
    .ZN(_20_)
  );
  OAI21_X2 _42_ (
    .A1(_19_),
    .A2(_18_),
    .B(_20_),
    .ZN(_21_)
  );
  XOR2_X1 _43_ (
    .A1(c[4]),
    .A2(_21_),
    .Z(_07_)
  );
  NAND2_X1 _44_ (
    .A1(c[4]),
    .A2(_21_),
    .ZN(_22_)
  );
  XNOR2_X1 _45_ (
    .A1(c[5]),
    .A2(_22_),
    .ZN(_08_)
  );
  NAND3_X1 _46_ (
    .A1(c[4]),
    .A2(c[5]),
    .A3(_21_),
    .ZN(_23_)
  );
  XNOR2_X1 _47_ (
    .A1(c[6]),
    .A2(_23_),
    .ZN(_03_)
  );
  NAND4_X2 _48_ (
    .A1(c[4]),
    .A2(c[6]),
    .A3(c[5]),
    .A4(_21_),
    .ZN(_24_)
  );
  XNOR2_X1 _49_ (
    .A1(c[7]),
    .A2(_24_),
    .ZN(_04_)
  );
  XOR2_X1 _50_ (
    .A1(c[1]),
    .A2(c[5]),
    .Z(_25_)
  );
  XNOR2_X1 _51_ (
    .A1(_12_),
    .A2(_25_),
    .ZN(_02_)
  );
  INV_X1 _52_ (
    .I(c[7]),
    .ZN(_26_)
  );
  NOR2_X2 _53_ (
    .A1(_26_),
    .A2(_24_),
    .ZN(_01_)
  );
  DFFRNQ_X1 _54_ (
    .CLK(clk),
    .D(a[0]),
    .Q(x[6]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _55_ (
    .CLK(clk),
    .D(a[1]),
    .Q(x[7]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _56_ (
    .CLK(clk),
    .D(a[2]),
    .Q(x[8]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _57_ (
    .CLK(clk),
    .D(a[3]),
    .Q(x[9]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _58_ (
    .CLK(clk),
    .D(a[4]),
    .Q(x[10]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _59_ (
    .CLK(clk),
    .D(a[5]),
    .Q(x[11]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _60_ (
    .CLK(clk),
    .D(a[6]),
    .Q(x[12]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _61_ (
    .CLK(clk),
    .D(a[7]),
    .Q(x[13]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _62_ (
    .CLK(clk),
    .D(c[0]),
    .Q(z[0]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _63_ (
    .CLK(clk),
    .D(c[1]),
    .Q(z[1]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _64_ (
    .CLK(clk),
    .D(c[2]),
    .Q(z[2]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _65_ (
    .CLK(clk),
    .D(c[3]),
    .Q(z[3]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _66_ (
    .CLK(clk),
    .D(_00_),
    .Q(z[4]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _67_ (
    .CLK(clk),
    .D(_02_),
    .Q(z[5]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _68_ (
    .CLK(clk),
    .D(_05_),
    .Q(z[6]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _69_ (
    .CLK(clk),
    .D(_06_),
    .Q(z[7]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _70_ (
    .CLK(clk),
    .D(_07_),
    .Q(z[8]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _71_ (
    .CLK(clk),
    .D(_08_),
    .Q(z[9]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _72_ (
    .CLK(clk),
    .D(_03_),
    .Q(z[10]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _73_ (
    .CLK(clk),
    .D(_04_),
    .Q(z[11]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _74_ (
    .CLK(clk),
    .D(_01_),
    .Q(z[12]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _75_ (
    .CLK(clk),
    .D(b[2]),
    .Q(y[0]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _76_ (
    .CLK(clk),
    .D(b[3]),
    .Q(y[1]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _77_ (
    .CLK(clk),
    .D(b[4]),
    .Q(y[2]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _78_ (
    .CLK(clk),
    .D(b[5]),
    .Q(y[3]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _79_ (
    .CLK(clk),
    .D(b[6]),
    .Q(y[4]),
    .RN(1'b1)
  );
  DFFRNQ_X1 _80_ (
    .CLK(clk),
    .D(b[7]),
    .Q(y[5]),
    .RN(1'b1)
  );
  assign { x[15:14], x[5:0] } = 8'b00000000;
  assign y[15:6] = 10'b0000000000;
  assign z[15:13] = 3'b000;
endmodule
